### ISSUE TITLE
Exclude /metrics from metrics

### ISSUE THREAD

**Issue by guerda** [piotrmaslanka/fastapi-satella-metrics#1]
I really like your plugin, it's a great addition to FastAPI.
Currently, the metrics are also created for endpoint /metrics. This leads to the (interesting) situation that the metrics are increasing more and more if prometheus is crawling the page.

Would it be sensible/possible to deactivate the metrics for /metrics?
Not sure if it should be configurable though.

**Comment by piotrmaslanka** [comment]
This project will be further developed as [Dronehub/fastapi-satella-metrics](https://github.com/Dronehub/fastapi-satella-metrics/). Someone will get over to this issue tomorrow and fix it.

**Comment by piotrmaslanka** [comment]
@guerda be prepared for a major API change. After all, it will be version 2.0 :D

**Comment by piotrmaslanka** [comment]
@NorbertOzga
